### ISSUE TITLE
Divider height

### ISSUE THREAD

**Issue by ivanmem** [andyhorn/flutter_resizable_container#20]
Currently, the library has a dividerWidth property, which is similar to the [thickness](https://api.flutter.dev/flutter/material/Divider/thickness.html) of a divider. However, the term is misleading, as it actually refers to the width of the line, not the separator itself.

Are there plans to introduce a property similar to [Divider height](https://api.flutter.dev/flutter/material/Divider/height.html), which would allow us to set the actual width of the divider, potentially making it larger than the divider's size?

**Comment by andyhorn** [comment]
This has been added in #26 - however, I used the terminology `thickness` to refer to the thickness of the visible line and `size` to refer to the total space taken up by the divider. Does that work? 

I didn't want to use `height` or `width` because the divider can be horizontal or vertical, so the best I could come up with was `size`.

**Comment by andyhorn** [comment]
This was included with release 1.0.0
